### ISSUE TITLE
Need a example code With redux-saga or next-redux-saga with i18

### ISSUE THREAD

**Issue by SathyanaryanaNaidu** [nextjs-boilerplate/next.js-redux-helper#1]
Hi , can you please provide example with redux-saga

**Comment by postor** [comment]
You can use less code to make redux work with next ssr with this reop, this repo does not provied i18n functionality.
Do you mean this? https://github.com/nextjs-boilerplate/next-i18n-helper  this make i18n with ssr easier, no matter whatever store you use
